package br.gov.ce.pge.gestao.enums;

public enum RespostaErro {
    RECUPERAR_SENHA_USUARIO_INTERNO, RECUPERAR_SENHA_USUARIO_INATIVO, RECUPERACAO_JA_ENVIADO, EMAIL_NAO_CADASTRADO, CODIGO_EXPIRADO, RECUPERAR_SENHA_USUARIO_BLOQUEADO
}
