stages:
  - build-dev
  - deploy-dev
  - build-test
  - deploy-test
  - build-hom
  - deploy-hom

build-dev:
  stage: build-dev
  image: google/cloud-sdk
  script:
    - echo "$BASE64_GOOGLE_CLOUD_CREDENTIALS" > /tmp/key.json
    - gcloud auth activate-service-account --key-file /tmp/key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud auth configure-docker
    - sed "s/\$IMAGE/ms-api-gateway-dev:${CI_COMMIT_SHORT_SHA}/g" cloudbuild.yaml > cloudbuild_deploy.yaml
    - gcloud builds submit --config=cloudbuild_deploy.yaml .
  only:
    - dev
  when: manual


deploy-dev:
  stage: deploy-dev
  image: google/cloud-sdk
  script:
    - echo "$BASE64_GOOGLE_CLOUD_CREDENTIALS" > /tmp/key.json
    - gcloud auth activate-service-account --key-file /tmp/key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud auth configure-docker
    - gcloud container clusters get-credentials pge-ce-cluster-dev --zone southamerica-east1-b --project pge-ce-dev-a937
    - sed "s/\$IMAGE/ms-api-gateway-dev:${CI_COMMIT_SHORT_SHA}/g" .k8s/dev-deployment.yaml | kubectl apply -f -
  only:
    - dev
  needs:
    - build-dev

build-test:
  stage: build-test
  image: google/cloud-sdk
  script:
    - echo "$BASE64_GOOGLE_CLOUD_CREDENTIALS" > /tmp/key.json
    - gcloud auth activate-service-account --key-file /tmp/key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud auth configure-docker
    - sed "s/\$IMAGE/ms-api-gateway-test:${CI_COMMIT_SHORT_SHA}/g" cloudbuild.yaml > cloudbuild_deploy.yaml
    - gcloud builds submit --config=cloudbuild_deploy.yaml .
  only:
    - test
  when: manual


deploy-test:
  stage: deploy-test
  image: google/cloud-sdk
  script:
    - echo "$BASE64_GOOGLE_CLOUD_CREDENTIALS" > /tmp/key.json
    - gcloud auth activate-service-account --key-file /tmp/key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud auth configure-docker
    - gcloud container clusters get-credentials pge-ce-cluster-dev --zone southamerica-east1-b --project pge-ce-dev-a937
    - sed "s/\$IMAGE/ms-api-gateway-test:${CI_COMMIT_SHORT_SHA}/g" .k8s/test-deployment.yaml | kubectl apply -f -
  only:
    - test
  needs:
    - build-test

build-hom:
  stage: build-hom
  image: google/cloud-sdk
  script:
    - echo "$BASE64_GOOGLE_CLOUD_CREDENTIALS" > /tmp/key.json
    - gcloud auth activate-service-account --key-file /tmp/key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud auth configure-docker
    - sed "s/\$IMAGE/ms-api-gateway-hom:${CI_COMMIT_SHORT_SHA}/g" cloudbuild.yaml > cloudbuild_deploy.yaml
    - gcloud builds submit --config=cloudbuild_deploy.yaml .
  only:
    - hom
  when: manual

deploy-hom:
  stage: deploy-hom
  image: google/cloud-sdk
  script:
    - echo "$BASE64_GOOGLE_CLOUD_CREDENTIALS" > /tmp/key.json
    - gcloud auth activate-service-account --key-file /tmp/key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud auth configure-docker
    - gcloud container clusters get-credentials pge-ce-cluster-dev --zone southamerica-east1-b --project pge-ce-dev-a937
    - sed "s/\$IMAGE/ms-api-gateway-hom:${CI_COMMIT_SHORT_SHA}/g" .k8s/hom-deployment.yaml | kubectl apply -f -
  only:
    - hom
  needs:
    - build-hom
