<!doctype html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport"
    content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
</head>

<body style="font-family: sans-serif;">
  <div style="margin:0;padding:0;background-color:#9edf8f">
    <div style="background-color:#003334;width:100%;">
      <div style="background-color:#003334;margin:0 auto;max-width:700px;width:100%">
        <table role="presentation" style="width:100%;border-collapse:collapse;border:0;border-spacing:0">
          <tbody>
            <tr style="vertical-align:center">
              <td style="vertical-align:center;padding:20px">
                <table role="presentation" style="width:100%;border-collapse:collapse;border:0;border-spacing:0">
                  <tbody>
                    <tr style="vertical-align:center">
                      <td width="100%" align="center" style="font-size:28px;color:#ffffff;font-weight:700">
                        <img style="width:300px;padding-left:32px"
                          src="https://www.pge.ce.gov.br/wp-content/uploads/sites/47/2021/05/logo-site-pge-pagina-principal-1-1.png"
                          alt="Logo do governo do estado do Ceará" class="CToWUd" data-bit="iit">
                      </td>

                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
            <tr>
              <td
                style="border-top-left-radius:10px;border-top-right-radius:10px;padding:40px 28px 20px;background-color:#ffffff;font-weight:700;color:#2d4040;font-size:20px">
                Olá, ${nomeUsuario}!
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div style="background-color:#eaf7eb;width:100%">
      <div style="background-color:#eaf7eb;margin:0 auto;max-width:700px;width:100%">
        <table role="presentation" style="width:100%;border-collapse:collapse;border:0;border-spacing:0">
          <tbody>

            <tr>
              <td align="center"
                style="text-align:justify;background-color:#ffffff;line-height:22px;font-weight:400;font-size:16px;color:#2d4040;padding:20px 35px 40px">
                Seu código de verificação para alteração de senha é:
              </td>
            </tr>

            <tr>
              <td align="center"
                style="background-color:#ffffff;padding:0 28px;border-bottom-left-radius:10px;border-bottom-right-radius:10px">
                <table style="padding-bottom:40px">
                  <tbody>
                    <tr>
                      <td
                        style="border-top-left-radius:10px;border-top-right-radius:10px;padding:40px 28px 20px;background-color:#ffffff;font-weight:700;color:#2d4040;font-size:20px">
                        ${codigo}
                      </td>
                    </tr>

                  </tbody>
                </table>
              </td>
            </tr>
            <tr>
              <td
                align="center"
                style="
                  text-align: center;
                  border-bottom-left-radius: 10px;
                  border-bottom-right-radius: 10px;
                  background-color: #ffffff;
                  line-height: 12px;
                  font-weight: 700;
                  font-size: 12px;
                  color: #003334;
                  padding: 20px 35px 30px;
                "
              >
                <p>
                  Esse e-mail é enviado de forma automática e não deve ser
                  respondido.
                </p>
                <p>${nomeSistema} - Cadastro do Usuário</p>
              </td>
            </tr>
            <tr>
              <td style="padding-bottom:80px">&nbsp;</td>
            </tr>
          </tbody>
        </table>
        <div class="yj6qo"></div>
        <div class="adL">
        </div>
      </div>
      <div class="adL">
      </div>
    </div>
    <div class="adL">

    </div>
  </div>
</body>