apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-pge-inscricao-divida
  namespace: homol
  labels:
    app: ms-pge-inscricao-divida
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-pge-inscricao-divida
  template:
    metadata:
      labels:
        app: ms-pge-inscricao-divida
    spec:
      containers:
        - name: ms-pge-inscricao-divida
          image: gcr.io/pge-ce-dev-a937/$IMAGE
          env:
            - name: DB_USER
              value: "db_pge_user"

            - name: DB_PASS
              value: '[^VLJG-";\nly@OA'

            - name: DB_DATABASE
              value: 'db_inscricao_divida_homol'

            - name: DB_HOST
              value: '10.102.32.5'

            - name: DB_PORT
              value: '5432'

            - name: EUREKA_SERVER
              value: "http://ms-eureka-server-service.homol.svc.cluster.local:8761/eureka"
            
            - name: GESTAO_SERVICE
              value: "http://ms-gestao-atributos-divida-service.homol.svc.cluster.local:8502"

            - name: BUCKET_GOOGLE_CLOUD_CREDENTIALS
              value: "/opt/google/credentials.json"

            - name: FILE_SERVICE
              value: "FileServiceGCP"

            - name: PATH_BUCKET_PGE
              value: "bucket_inscricao_divida_homol"     
          ports:
            - containerPort: 8508
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: ms-pge-inscricao-divida
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 5
    type: HTTP
    requestPath: /health-check
    port: 8508
