server:
  port: 8505

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}

spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  application:
    name: ms-pge-oauth
    
    
api:
  secutiry:
    token:
      secret: ${JWT_SECRET}
      

ms:
  service:
    user: ${USER_SERVICE}
    
ldap:
  domain: pge.ce.gov.br
  url: ldap://192.168.2.21:389    
      
