apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-pge-portal-colaborador
  namespace: homol
  labels:
    app: ms-pge-portal-colaborador
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-pge-portal-colaborador
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: ms-pge-portal-colaborador
    spec:
      containers:
      - name: ms-pge-portal-colaborador
        image: gcr.io/pge-ce-dev-a937/$IMAGE
        env:
        - name: EUREKA_SERVER
          value: "http://ms-eureka-server-service.homol.svc.cluster.local:8761/eureka"
        - name: PASSWORD
          value: "t9eWOgf200£L"
        - name: URL
          value: "jdbc:postgresql://192.168.2.60:5434/db_desenv?currentSchema=adm_cadcolaborador"
        - name: USER
          value: "golden_cadcolaborador"
        ports:
        - containerPort: 8507
