CREATE TABLE "tb_devedor" (
	"ci_devedor" UUID NOT NULL,
	"dt_atualizacao" TIMESTAMP NULL DEFAULT NULL,
	"dt_criacao" TIMESTAMP NOT NULL,
	"nm_usuario_atualizacao" VARCHAR(255) NULL DEFAULT NULL,
	"nm_usuario_cadastro" VARCHAR(255) NULL DEFAULT NULL,
	"ds_bairro_devedor" VARCHAR(100) NOT NULL,
	"nr_cep_devedor" VARCHAR(15) NOT NULL,
	"nr_cgf_devedor" VARCHAR(15) NULL DEFAULT NULL,
	"ds_complemento_devedor" VARCHAR(255) NULL DEFAULT NULL,
	"nr_contato_devedor" VARCHAR(15) NULL DEFAULT NULL,
	"ds_distrito_devedor" VARCHAR(70) NULL DEFAULT NULL,
	"nr_documento_devedor" VARCHAR(14) NOT NULL,
	"ds_email_devedor" VARCHAR(255) NULL DEFAULT NULL,
	"ds_logradouro_devedor" VARCHAR(255) NOT NULL,
	"ds_municipio_devedor" VARCHAR(100) NOT NULL,
	"nm_devedor" VARCHAR(255) NOT NULL,
	"nr_endereco_devedor" VARCHAR(10) NOT NULL,
	"ds_tipo_contato_devedor" VARCHAR(50) NULL DEFAULT NULL,
	"ds_tipo_pessoa_devedor" VARCHAR(50) NOT NULL,
	"ds_uf_devedor" VARCHAR(20) NOT NULL,
	CONSTRAINT "pk_tbdevedor" PRIMARY KEY ("ci_devedor")
);


CREATE TABLE "tb_divida" (
	"ci_divida" UUID NOT NULL,
	"dt_atualizacao" TIMESTAMP NULL DEFAULT NULL,
	"dt_criacao" TIMESTAMP NOT NULL,
	"nm_usuario_atualizacao" VARCHAR(255) NULL DEFAULT NULL,
	"nm_usuario_cadastro" VARCHAR(255) NULL DEFAULT NULL,
	"dt_constituicao_definitiva" DATE NULL DEFAULT NULL,
	"dt_documento" DATE NULL DEFAULT NULL,
	"dt_processo" DATE NULL DEFAULT NULL,
	"dt_termo_revelia" DATE NULL DEFAULT NULL,
	"dt_transito_julgado" DATE NULL DEFAULT NULL,
	"ds_disposicoes_legais" VARCHAR(500) NOT NULL,
	"nr_guia_itcd" VARCHAR(50) NULL DEFAULT NULL,
	"cd_origem_debito" UUID NOT NULL,
	"cd_tipo_receita" UUID NOT NULL,
	"ds_inexistencia_suspensivas" VARCHAR(500) NULL DEFAULT NULL,
	"ds_natureza_fundamentacao" VARCHAR(500) NULL DEFAULT NULL,
	"nm_anexo_processo" VARCHAR(255) NULL DEFAULT NULL,
	"nr_acordao" VARCHAR(50) NULL DEFAULT NULL,
	"nr_chassi" VARCHAR(50) NULL DEFAULT NULL,
	"nr_documento" VARCHAR(10) NULL DEFAULT NULL,
	"nr_oficio" VARCHAR(50) NULL DEFAULT NULL,
	"nr_processo_administrativo" VARCHAR(50) NULL DEFAULT NULL,
	"ds_placa_veiculo" VARCHAR(50) NULL DEFAULT NULL,
	"nr_protocolo_judicial" VARCHAR(50) NULL DEFAULT NULL,
	"sq_parcelamento" VARCHAR(50) NULL DEFAULT NULL,
	"ds_termo_revelia" VARCHAR(50) NULL DEFAULT NULL,
	"tp_documento" VARCHAR(50) NULL DEFAULT NULL,
	"tp_processo" VARCHAR(50) NULL DEFAULT NULL,
	CONSTRAINT "pk_tbdivida" PRIMARY KEY ("ci_divida")
);

CREATE TABLE "tb_inscricao" (
	"ci_inscricao" UUID NOT NULL,
	"dt_atualizacao" TIMESTAMP NULL DEFAULT NULL,
	"dt_criacao" TIMESTAMP NOT NULL,
	"nm_usuario_atualizacao" VARCHAR(255) NULL DEFAULT NULL,
	"nm_usuario_cadastro" VARCHAR(255) NULL DEFAULT NULL,
	"ds_status_inscricao" VARCHAR(255) NULL DEFAULT NULL,
	"cd_devedor" UUID NULL DEFAULT NULL,
	"cd_divida" UUID NULL DEFAULT NULL,
	CONSTRAINT "pk_tbinscricao" PRIMARY KEY ("ci_inscricao"),
	CONSTRAINT "fk_tbinscricao_tbdevedor" FOREIGN KEY ("cd_devedor") REFERENCES "tb_devedor" ("ci_devedor") ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT "fk_tbinscricao_tbdivida" FOREIGN KEY ("cd_divida") REFERENCES "tb_divida" ("ci_divida") ON UPDATE NO ACTION ON DELETE NO ACTION
);


CREATE TABLE "tb_corresponsavel" (
	"ci_corresponsavel" UUID NOT NULL,
	"dt_atualizacao" TIMESTAMP NULL DEFAULT NULL,
	"dt_criacao" TIMESTAMP NOT NULL,
	"nm_usuario_atualizacao" VARCHAR(255) NULL DEFAULT NULL,
	"nm_usuario_cadastro" VARCHAR(255) NULL DEFAULT NULL,
	"ds_bairro_corresponsavel" VARCHAR(100) NOT NULL,
	"nr_cep_corresponsavel" VARCHAR(15) NOT NULL,
	"nr_cgf_corresponsavel" VARCHAR(15) NULL DEFAULT NULL,
	"ds_complemento_corresponsavel" VARCHAR(255) NULL DEFAULT NULL,
	"nr_contato_corresponsavel" VARCHAR(15) NULL DEFAULT NULL,
	"ds_distrito_corresponsavel" VARCHAR(70) NULL DEFAULT NULL,
	"nr_documento_corresponsavel" VARCHAR(14) NOT NULL,
	"ds_email_corresponsavel" VARCHAR(255) NULL DEFAULT NULL,
	"ds_logradouro_corresponsavel" VARCHAR(255) NOT NULL,
	"ds_municipio_corresponsavel" VARCHAR(100) NOT NULL,
	"nm_corresponsavel" VARCHAR(250) NOT NULL,
	"nr_endereco_corresponsavel" VARCHAR(10) NOT NULL,
	"ds_qualificacao_corresponsavel" VARCHAR(100) NULL DEFAULT NULL,
	"ds_tipo_contato_corresponsavel" VARCHAR(50) NULL DEFAULT NULL,
	"ds_tipo_pessoa_corresponsavel" VARCHAR(50) NOT NULL,
	"ds_uf_corresponsavel" VARCHAR(20) NOT NULL,
	"cd_inscricao" UUID NULL DEFAULT NULL,
	CONSTRAINT "pk_tbcorresponsavel" PRIMARY KEY ("ci_corresponsavel"),
	CONSTRAINT "fk_tbcorresponsavel_tbinscricao" FOREIGN KEY ("cd_inscricao") REFERENCES "tb_inscricao" ("ci_inscricao") ON UPDATE NO ACTION ON DELETE NO ACTION
);


CREATE TABLE "tb_debito" (
	"ci_debito" UUID NOT NULL,
	"dt_atualizacao" TIMESTAMP NULL DEFAULT NULL,
	"dt_criacao" TIMESTAMP NOT NULL,
	"nm_usuario_atualizacao" VARCHAR(255) NULL DEFAULT NULL,
	"nm_usuario_cadastro" VARCHAR(255) NULL DEFAULT NULL,
	"dt_constituicao_definitiva" DATE NULL DEFAULT NULL,
	"dt_vencimento" DATE NOT NULL,
	"ds_referencia_final" VARCHAR(7) NOT NULL,
	"ds_referencia_inicial" VARCHAR(7) NOT NULL,
	"vl_multa_debito" NUMERIC(19,2) NOT NULL,
	"vl_principal_debito" NUMERIC(19,2) NOT NULL,
	"cd_inscricao" UUID NULL DEFAULT NULL,
	CONSTRAINT "pk_tbdebito" PRIMARY KEY ("ci_debito"),
	CONSTRAINT "fk_tbdebito_tbinscricao" FOREIGN KEY ("cd_inscricao") REFERENCES "tb_inscricao" ("ci_inscricao") ON UPDATE NO ACTION ON DELETE NO ACTION
);
