DROP TABLE "tb_sucessor_contato" CASCADE;
DROP TABLE "tb_corresponsavel_contato" CASCADE;
DROP TABLE "tb_devedor_contato" CASCADE;
DROP TABLE "tb_devedor" CASCADE;
DROP TABLE "tb_sucessor" CASCADE;
DROP TABLE "tb_corresponsavel" CASCADE;
DROP TABLE "tb_inscricao_devedor" CASCADE;
DROP TABLE "tb_divida_anexo" CASCADE;
DROP TABLE "tb_inscricao" CASCADE;
