apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-eureka-server
  namespace: dev
  labels:
    app: ms-eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-eureka-server
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: ms-eureka-server

    spec:
      containers:
      - name: backend
        image: gcr.io/pge-ce-dev-a937/ms-eureka-server-dev:latest
        ports:
        - containerPort: 8761