version: '3'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "db_pge_user"
      TZ: "America/Sao_Paulo"
    ports:
      - "5432:5432"
    networks:
      - docker-network
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      TZ: "America/Sao_Paulo"
    ports:
      - "16543:80"
    depends_on:
      - postgres-db
    networks:
      - docker-network
    restart: always

networks:
  docker-network:
    driver: bridge